language: ruby
rvm:
 - 2.6.5

services:
  - postgresql

before_script:
  - psql -c 'CREATE DATABASE chitter;' -U postgres
  - psql -c 'CREATE TABLE peep (id SERIAL PRIMARY KEY, body VARCHAR(200), time time);' -U postgres


script:
  - bundle exec rspec
